In [1]:
import streamlit as st
st.title("welcome to my first model")


2024-05-20 17:04:08.825 
  command:

    streamlit run C:\Users\Babar Raheem\anaconda3\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]


DeltaGenerator()

In [2]:
import tensorflow as tf
import tensorflow as keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import InputLayer,Dense,Flatten


In [3]:

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()     #x_train = 60000
                                                                              # test set = 10000

In [4]:
x_train.shape


(60000, 28, 28)

In [5]:
##to ploat a single digit
import matplotlib.pyplot as plt
plt.imshow(x_train[1])

In [6]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [7]:
##let standarize the data to make convergence fast
X_train = x_train/255             #to centralized data between 0 and 1
X_test = x_test/255

In [8]:
#now lets create AAN model
model = Sequential()
model.add(Flatten(input_shape = (28,28)))    #Flatten() convert two dimention matrix into 1 dimention i.e columns into rows
model.add(Dense(128,activation = 'relu'))    #hidden layer 1         #Flatten funtion will pass total number of input to "Dense". here total nodes = 128
model.add(Dense(10,activation = "softmax"))  #hidden layer 2    #output will be 10 because there are 10 classes #here we use "softmax" activation funtion because of multiple classes outcome

C:\Users\Babar Raheem\anaconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       100,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 101,770 (397.54 KB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
#lets compile and train the model

model.compile(loss = 'sparse_categorical_crossentropy', optimizer = 'Adam')
model.fit(X_train,y_train,epochs= 10 , validation_split = 0.2)

Epoch 1/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 0.4749 - val_loss: 0.1681
Epoch 2/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 0.1407 - val_loss: 0.1166
Epoch 3/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 0.0907 - val_loss: 0.1204
Epoch 4/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 0.0666 - val_loss: 0.1014
Epoch 5/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 0.0522 - val_loss: 0.0974
Epoch 6/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 0.0385 - val_loss: 0.0910
Epoch 7/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 0.0290 - val_loss: 0.0952
Epoch 8/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - loss: 0.0251 - val_loss: 0.1005
Epoch 9/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 0.0197 - val_loss: 0.0945
Epoch 10/10
1500/1500 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - loss: 0.0170 - val_loss: 0.1082


In [11]:
y_prob = model.predict(X_test)   #here model will predict the probability of each input b/w 0 , 9

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step


In [12]:
#now to find out the maximum probability of digit inside each array
y_predict = y_prob.argmax(axis =  1)
y_predict
#on the output the first picture in the input has predicted as 5

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [13]:
#let's check the accuracy of our model
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predict)

0.972

In [ ]:
plt.imshow(X_test[50])

In [ ]:
#now to check the prediction of our model

model.predict(X_test[50].reshape(1,28,28)).argmax(axis = 1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


array([6], dtype=int64)